apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Param environment in parent exists
on:
  workflow_dispatch:
    inputs:
      targetenv:
        type: string
        required: true
        default: environment_mlcb_top2
jobs:
  testhardocedenv:
    environment: environment_mlcb_top2
    steps:
      - name: Print testvar
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "testvar:"
      - name: Print testsec
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "testvar:"
  testparamenv:
    environment: ${{ inputs.targetenv }}
    steps:
      - name: Print testvar
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "testvar:"
      - name: Print testsec
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "testvar:"
